# ===============================
# Oracle Database
# ===============================

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=STUDENTDB
spring.datasource.password=Student1230
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# ===============================
# Server
# ===============================

server.port=8080


# ===============================
# Session
# ===============================

server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.timeout=2m